<?php

namespace App\Providers;

use App\Models\System;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\View;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        $arrNavItems =[
            "Home" => '/', 
            "About Us" => '/aboutus', 
            "Tour" => '/tour',
            "Contact Us" => '/contact',
        ];
        View::share('landingNavbar', $arrNavItems);

        $arrNationality = [
            "Afghan",
            "Albanian",
            "Algerian",
            "American",
            "American Samoan",
            "Andorran",
            "Angolan",
            "Anguillan",
            "Antiguan and Barbudan",
            "Argentine",
            "Armenian",
            "Aruban",
            "Ascension Islander",
            "Australian",
            "Austrian",
            "Azerbaijani",
            "Bahamian",
            "Bahraini",
            "Bangladeshi",
            "Barbadian",
            "Belarusian",
            "Belgian",
            "Belizean",
            "Beninese",
            "Bermudian",
            "Bhutanese",
            "Bolivian",
            "Bosnian and Herzegovinian",
            "Botswana",
            "Brazilian",
            "British",
            "British Indian Ocean Territory",
            "British Virgin Islander",
            "Bruneian",
            "Bulgarian",
            "Burkinabé",
            "Burundian",
            "Cambodian",
            "Cameroonian",
            "Canadian",
            "Cape Verdean",
            "Caribbean Netherlands",
            "Cayman Islander",
            "Central African",
            "Chadian",
            "Chilean",
            "Chinese",
            "Christmas Island",
            "Cocos Islander",
            "Colombian",
            "Comorian",
            "Congolese",
            "Congolese",
            "Cook Islander",
            "Costa Rican",
            "Croatian",
            "Cuban",
            "Curaçaoan",
            "Cypriot",
            "Czech",
            "Danish",
            "Djiboutian",
            "Dominican",
            "Dominican",
            "East Timorese",
            "Ecuadorian",
            "Egyptian",
            "Emirati",
            "Equatorial Guinean",
            "Eritrean",
            "Estonian",
            "Ethiopian",
            "Falkland Islander",
            "Faroese",
            "Fijian",
            "Filipino",
            "Finnish",
            "French",
            "French Guianese",
            "French Polynesian",
            "Gabonese",
            "Gambian",
            "Georgian",
            "German",
            "Ghanaian",
            "Gibraltarian",
            "Greek",
            "Greenlandic",
            "Grenadian",
            "Guadeloupean",
            "Guamanian",
            "Guatemalan",
            "Guinean",
            "Bissau-Guinean",
            "Guyanese",
            "Haitian",
            "Honduran",
            "Hong Kong",
            "Hungarian",
            "I-Kiribati",
            "Icelandic",
            "Indian",
            "Indonesian",
            "Iranian",
            "Iraqi",
            "Irish",
            "Israeli",
            "Italian",
            "Jamaican",
            "Japanese",
            "Jordanian",
            "Kazakhstani",
            "Kenyan",
            "Kittitian and Nevisian",
            "Kosovan",
            "Kuwaiti",
            "Kyrgyzstani",
            "Laotian",
            "Latvian",
            "Lebanese",
            "Basotho",
            "Liberian",
            "Libyan",
            "Liechtensteiner",
            "Lithuanian",
            "Luxembourger",
            "Macanese",
            "Madagascan",
            "Malawian",
            "Malaysian",
            "Maldivian",
            "Malian",
            "Maltese",
            "Marshallese",
            "Martinican",
            "Mauritanian",
            "Mauritian",
            "Mexican",
            "Micronesian",
            "Moldovan",
            "Monegasque",
            "Mongolian",
            "Montenegrin",
            "Montserratian",
            "Moroccan",
            "Mozambican",
            "Myanmar",
            "Namibian",
            "Nauruan",
            "Nepali",
            "Ni-Vanuatu",
            "Nigerien",
            "Nigerian",
            "Niuean",
            "North Korean",
            "North Macedonian",
            "Northern Mariana Islander",
            "Norwegian",
            "Omani",
            "Pakistani",
            "Palauan",
            "Palestinian",
            "Panamanian",
            "Papua New Guinean",
            "Paraguayan",
            "Peruvian",
            "Polish",
            "Portuguese",
            "Puerto Rican",
            "Qatari",
            "Réunionese",
            "Romanian",
            "Russian",
            "Rwandan",
            "Saint Helenian",
            "Saint Kitts and Nevis",
            "Saint Lucian",
            "Saint Martinoise",
            "Saint Pierrais",
            "Saint Vincentian",
            "Sahrawi",
            "Samoan",
            "San Marinese",
            "São Toméan",
            "Saudi Arabian",
            "Senegalese",
            "Serbian",
            "Seychellois",
            "Sierra Leonean",
            "Singaporean",
            "Sint Maartener",
            "Slovak",
            "Slovenian",
            "Solomon Islander",
            "Somali",
            "South African",
            "South Korean",
            "South Sudanese",
            "Spanish",
            "Sri Lankan",
            "Sudanese",
            "Surinamese",
            "Swazi",
            "Swedish",
            "Swiss",
            "Syrian",
            "Taiwanese",
            "Tajikistani",
            "Tanzanian",
            "Thai",
            "Togolese",
            "Tokelauan",
            "Tongan",
            "Trinidadian and Tobagonian",
            "Tunisian",
            "Turkish",
            "Turkmen",
            "Turks and Caicos Islander",
            "Tuvaluan",
            "U.S. Virgin Islander",
            "Ugandan",
            "Ukrainian",
            "Uruguayan",
            "Uzbekistani",
            "Vatican",
            "Venezuelan",
            "Vietnamese",
            "Vincentian",
            "Wallis and Futuna",
            "Yemeni",
            "Zambian",
            "Zimbabwean",
            "Åland Islander"
        ];
        
        
        View::share('nationality', $arrNationality);

        $arrCountries = [
            "Afghanistan",
            "Albania",
            "Algeria",
            "American Samoa",
            "Andorra",
            "Angola",
            "Anguilla",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Aruba",
            "Ascension Island",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bermuda",
            "Bhutan",
            "Bolivia",
            "Bosnia and Herzegovina",
            "Botswana",
            "Brazil",
            "British Indian Ocean Territory",
            "British Virgin Islands",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Cape Verde",
            "Caribbean Netherlands",
            "Cayman Islands",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Christmas Island",
            "Cocos (Keeling) Islands",
            "Colombia",
            "Comoros",
            "Congo (DRC)",
            "Congo (Republic)",
            "Cook Islands",
            "Costa Rica",
            "Côte d’Ivoire",
            "Croatia",
            "Cuba",
            "Curaçao",
            "Cyprus",
            "Czech Republic",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Eswatini",
            "Ethiopia",
            "Falkland Islands",
            "Faroe Islands",
            "Fiji",
            "Finland",
            "France",
            "French Guiana",
            "French Polynesia",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Gibraltar",
            "Greece",
            "Greenland",
            "Grenada",
            "Guadeloupe",
            "Guam",
            "Guatemala",
            "Guernsey",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hong Kong",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Isle of Man",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jersey",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Kosovo",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Macau",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marshall Islands",
            "Martinique",
            "Mauritania",
            "Mauritius",
            "Mayotte",
            "Mexico",
            "Micronesia",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Montserrat",
            "Morocco",
            "Mozambique",
            "Myanmar (Burma)",
            "Namibia",
            "Nauru",
            "Nepal",
            "Netherlands",
            "New Caledonia",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Niue",
            "Norfolk Island",
            "North Korea",
            "North Macedonia",
            "Northern Mariana Islands",
            "Norway",
            "Oman",
            "Pakistan",
            "Palau",
            "Palestine",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Portugal",
            "Puerto Rico",
            "Qatar",
            "Réunion",
            "Romania",
            "Russia",
            "Rwanda",
            "Saint Barthélemy",
            "Saint Helena",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Martin",
            "Saint Pierre and Miquelon",
            "Saint Vincent and the Grenadines",
            "Samoa",
            "San Marino",
            "São Tomé and Príncipe",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Sint Maarten",
            "Slovakia",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "South Korea",
            "South Sudan",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Svalbard and Jan Mayen",
            "Sweden",
            "Switzerland",
            "Syria",
            "Taiwan",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "Timor-Leste",
            "Togo",
            "Tokelau",
            "Tonga",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Turks and Caicos Islands",
            "Tuvalu",
            "U.S. Virgin Islands",
            "Uganda",
            "Ukraine",
            "United Arab Emirates",
            "United Kingdom",
            "United States",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Vatican City",
            "Venezuela",
            "Vietnam",
            "Wallis and Futuna",
            "Western Sahara",
            "Yemen",
            "Zambia",
            "Zimbabwe",
            "Åland Islands"
        ];
        
        View::share('countries', $arrCountries);
        $arrCur = [
            'USD' => '$',
            'EUR' => '€',
            'JPY' => '¥',
            'GBP' => '£',
            'CAD' => 'C$',
            'AUD' => 'A$',
            'CHF' => 'CHF',
            'CNY' => '¥',
            'INR' => '₹',
            'PHP' => '₱',
        ];

        View::share('currencies', $arrCur);
        View::share('currencyKey', array_keys($arrCur));

        // Should return TRUE or FALSE
        Gate::define('admin', function(System $system_user) {
            return $system_user->type === 0;
        });
        Gate::define('manager', function(System $system_user) {
            return $system_user->type === 1;
        });
        Gate::define('front-desk', function(System $system_user) {
            return $system_user->type === 2;
        });
    }
}
